export const INCREMENT = 'INCREMENT'
export const DECREMENT = 'DECREMENT'

export const GET_USER_PENDING = 'GET_USER_PENDING'
export const GET_USER_FULFILLED = 'GET_USER_FULFILLED'
export const GET_USER_REJECTED = 'GET_USER_REJECTED'